# Generated by Django 6.0 on 2026-01-03 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="estimated_fuel_cost",
            field=models.FloatField(default=0, help_text="Estimated fuel cost in USD"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="fuel_efficiency",
            field=models.FloatField(
                default=25.0,
                help_text="Vehicle fuel efficiency in MPG",
                validators=[
                    django.core.validators.MinValueValidator(5.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="fuel_price_per_gallon",
            field=models.FloatField(
                default=3.5,
                help_text="Fuel price per gallon in USD",
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="route_bounds",
            field=models.JSONField(
                blank=True, help_text="Route bounding box for map fitting", null=True
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="route_type",
            field=models.CharField(
                choices=[
                    ("fastest", "Fastest Route"),
                    ("scenic", "Scenic Route"),
                    ("custom", "Custom Route"),
                ],
                default="fastest",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="total_distance",
            field=models.FloatField(default=0, help_text="Total distance in miles"),
        ),
    ]
